cauldron:
  resource: '../andrii/cauldron/src/Controller/'
  type:     annotation
  prefix: '/andrii/cauldron'
  name_prefix: 'andrii_cauldron_'
mvp_office:
  resource: '../andrii/mvp_office/src/Controller/'
  type:     annotation
  prefix: '/andrii/mvp_office'
  name_prefix: 'andrii_mvp_office_'
write_solid:
  resource: '../andrii/write_solid/src/Controller/'
  type:     annotation
  prefix: '/andrii/write_solid'
  name_prefix: 'andrii_write_solid_'